### PR TITLE
Add dynamic column sizing to wsk activation list command

### PR DESCRIPTION
**Pull request by larandersson**
This addresses https://github.com/apache/incubator-openwhisk-client-go/issues/119 and adds dynamic sizing behavior to the *Kind* and *Status* columns, as well as skips the column heading if there are no activation records to display.

With this change, the behavior will be:

```wsk activation list --skip 20 --limit 5```
<pre>
Datetime            Activation ID                    Kind     Start Duration   Status  Entity
2019-03-14 14:49:11 847b942103bb4b43bb942103bb7b4376 nodejs:6 warm  2ms        success guest/helloworld:0.0.1
2019-03-14 14:47:48 d5c208b0336c40328208b0336ca03222 nodejs:6 cold  33ms       success guest/helloworld:0.0.1
2019-03-14 09:04:49 d8b4fb863117413ab4fb863117513af5 nodejs:6 cold  31ms       success guest/greeting:0.0.1
2019-03-12 19:28:25 daa12f0d612f4426a12f0d612f8426c4 nodejs:6 cold  129ms      success guest/greeting:0.0.1
2019-03-12 18:20:32 daa5acdcc48947e0a5acdcc489f7e04e nodejs:6 cold  116ms      success guest/greeting:0.0.1
</pre>

And, then for next pagination we can see how the columns change dynamically (see the Status and Entity columns):

```wsk activation list --skip 25 --limit 5```
<pre>
Datetime            Activation ID                    Kind     Start Duration   Status            Entity
2019-02-28 10:08:27 3d578d89fd0f4106978d89fd0f110650 nodejs:6 cold  741ms      success           guest/kafkaFeed:0.0.2
2019-02-27 15:17:05 05b8edb3f5aa40cbb8edb3f5aaf0cbc9 nodejs:6 warm  126ms      success           guest/kafkaFeed:0.0.2
2019-02-27 15:16:16 b18da1f06f4143718da1f06f41937150 nodejs:6 warm  129ms      success           guest/kafkaFeed:0.0.2
2019-02-27 15:14:28 5d8d23b5082d4dba8d23b5082d4dba8a nodejs:6 warm  99ms       application error guest/kafkaFeed:0.0.2
2019-02-27 15:10:34 3d7e4912dc224273be4912dc227273a9 nodejs:6 cold  966ms      success           guest/kafkaFeed:0.0.2
</pre>

This PR is dependent on https://github.com/apache/incubator-openwhisk-client-go/pull/120, and when that has been merged into client-go, the `build.gradle` file needs to be updated to the commit hash of that PR.

- [x] I have signed a CLA

### CODE REVIEW

**Comment by rabbah** [comment]
@larandersson I see this error in Travis

```
:buildDarwin386# github.com/apache/incubator-openwhisk-cli/commands
commands/activation.go:57:28: undefined: whisk.ActivationFilteredRow
commands/activation.go:107:53: undefined: whisk.ActivationFilteredRow
commands/activation.go:435:19: undefined: whisk.StatusCodes
commands/activation.go:439:71: undefined: whisk.StatusCodes
commands/activation.go:440:17: undefined: whisk.StatusCodes
commands/util.go:215:9: undefined: whisk.ActivationFilteredRow
commands/util.go:216:12: cannot range over collection (type interface {})
 FAILED
```

**Comment by larandersson** [comment]
@rabbah Did you observe the dependency to https://github.com/apache/incubator-openwhisk-client-go/pull/120? It's not expected to work until that PR has been merged.

**Comment by rabbah** [comment]
Thanks. Just merged it.

**Comment by larandersson** [comment]
@rabbah Updated *build.gradle*. Now it should work.

**Comment by larandersson** [comment]
@rabbah Updated *vendor.json* as well.

**Pull request merged**
